trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- script: |
    git remote add github https://github.com/kingsbayanalytics/portfolio.git
    git push github main
  displayName: 'Push to GitHub'
